package tasking

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"assistant-to/internal/db"
	"assistant-to/internal/intelligence"
)

// GenerateTaskInstructions creates a proper AT_INSTRUCTIONS.md spec file for a task
func GenerateTaskInstructions(root string, taskID int, title, description, targetFiles, difficulty, outputPath string) error {
	// Parse target files
	var targetFilesList []string
	if targetFiles != "" {
		targetFilesList = strings.Split(targetFiles, ",")
		for i := range targetFilesList {
			targetFilesList[i] = strings.TrimSpace(targetFilesList[i])
		}
	}

	// Build composition context
	ctx := &CompositionContext{
		Role:        "Builder",
		TaskID:      strconv.Itoa(taskID),
		TaskTitle:   title,
		TaskDesc:    description,
		TargetFiles: targetFilesList,
		Timestamp:   time.Now(),
		BasePath:    root,
	}

	// Try to load code intelligence context if target files exist
	codeIndexPath := filepath.Join(root, ".assistant-to", "code-intelligence.db")
	if _, err := os.Stat(codeIndexPath); err == nil && len(targetFilesList) > 0 {
		idx, err := intelligence.NewCodeIndex(codeIndexPath)
		if err == nil {
			defer idx.Close()

			// Gather file info for target files
			var fileContext strings.Builder
			for _, file := range targetFilesList {
				fileInfo, err := idx.GetFileInfo(file)
				if err == nil {
					fileContext.WriteString(fmt.Sprintf("\n### %s\n", file))
					fileContext.WriteString(fmt.Sprintf("- Package: %s\n", fileInfo.Package))
					if len(fileInfo.Types) > 0 {
						fileContext.WriteString(fmt.Sprintf("- Types: %s\n", strings.Join(fileInfo.Types, ", ")))
					}
					if len(fileInfo.Functions) > 0 {
						funcNames := strings.Join(fileInfo.Functions, ", ")
						if len(funcNames) > 100 {
							funcNames = funcNames[:100] + "..."
						}
						fileContext.WriteString(fmt.Sprintf("- Functions: %s\n", funcNames))
					}
				}
			}
			if fileContext.Len() > 0 {
				ctx.TaskDesc += "\n\n## Target File Context\n" + fileContext.String()
			}
		}
	}

	// Load expertise relevant to the task
	dbPath := filepath.Join(root, ".assistant-to", "state.db")
	database, err := db.Open(dbPath)
	if err == nil {
		defer database.Close()
		if err := database.InitSchema(); err == nil {
			// Search for relevant expertise based on target files
			var relevantExpertise []string
			for _, file := range targetFilesList {
				domain := filepath.Dir(file)
				entries, err := database.SearchExpertise(domain)
				if err == nil {
					for _, entry := range entries {
						relevantExpertise = append(relevantExpertise,
							fmt.Sprintf("[%s] %s: %s", entry.Type, entry.Domain, entry.Description))
					}
				}
			}
			ctx.Expertise = relevantExpertise
		}
	}

	// Try to use PromptComposer for rich spec generation
	promptsPath := filepath.Join(root, ".assistant-to", "prompts")
	if _, err := os.Stat(promptsPath); err == nil {
		composer, err := NewPromptComposer(promptsPath)
		if err == nil {
			content, err := composer.Compose("Builder", ctx)
			if err == nil {
				header := fmt.Sprintf(`# AT_INSTRUCTIONS.md
# Generated: %s
# Task ID: %s
# Difficulty: %s
# Target Files: %s
#
# This is an auto-generated task specification for assistant-to.
# Do not edit this file manually - update via 'dwight task update' instead.

`, time.Now().Format(time.RFC3339), ctx.TaskID, difficulty, targetFiles)

				fullContent := header + content
				return os.WriteFile(outputPath, []byte(fullContent), 0644)
			}
		}
	}

	// Fallback: Generate basic AT_INSTRUCTIONS.md
	spec := fmt.Sprintf(`# AT_INSTRUCTIONS.md
# Generated: %s
# Task ID: %d
# Difficulty: %s
# Target Files: %s
#
# This is an auto-generated task specification for assistant-to.
# Do not edit this file manually - update via 'dwight task update' instead.

## Task Overview

**Title:** %s
**ID:** %d
**Difficulty:** %s
**Status:** pending

## Description

%s

## Target Files

%s

## Constraints & Guidelines

- Work strictly within the specified target files
- Do not modify files outside the scope unless explicitly required
- Follow existing code patterns and conventions
- Write tests for any new functionality
- Ensure the code compiles and tests pass before completing
`, time.Now().Format(time.RFC3339), taskID, difficulty, targetFiles, title, taskID, difficulty, description, targetFiles)

	if len(ctx.Expertise) > 0 {
		spec += "\n## Relevant Expertise\n\n"
		for _, exp := range ctx.Expertise {
			spec += fmt.Sprintf("- %s\n", exp)
		}
	}

	spec += `
## Completion Criteria

1. All requirements in the Description are met
2. Code follows project conventions
3. Tests pass (if applicable)
4. No breaking changes introduced
5. Changes are committed to the worktree

## Next Steps

1. Review this specification carefully
2. Examine the target files to understand current state
3. Implement the required changes
4. Test your changes thoroughly
5. Signal completion by creating a .builder_complete file in the worktree
`

	return os.WriteFile(outputPath, []byte(spec), 0644)
}
